name: Build docs
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    if: github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]'
    uses: doplaydo/pdk-ci-workflow/.github/workflows/pages.yml@{{VERSION}}
